### ISSUE TITLE
Cannot find module 'rxjs/observable'

### ISSUE THREAD

**Issue by junibrosas** [AngularClass/angular2-idle-preload#10]
I hosted my angular application on a linux server and got error "Cannot find module 'rxjs/observable'" on the build process.

I ended up editing the @angularclass index.d.ts from rxjs/observable to rxjs/Observable

**Comment by junibrosas** [comment]
Oh, the repository was actually renamed from @angularclass/idle-preload.

**Comment by PatrickJS** [comment]
3.0.0 published
