### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Tuizi** [AngularClass/angular2-idle-preload#4]
I'm using this starter: https://github.com/qdouble/angular-webpack2-starter

I have created few more lazy routes than the starter have and I have replaced:
```javascript
RouterModule.forRoot(routes, {preloadingStrategy: PreloadAllModules}),
```
by
```javascript
IdlePreloadModule.forRoot(), // forRoot ensures the providers are only created once
RouterModule.forRoot([], { useHash: false, preloadingStrategy: IdlePreload }),
```

But when starting the application with `yarn start:hmr` the main route is loaded but not child route, this is working well with `PreloadAllModules` but not with `IdlePreload`.

Nothing happens, modules are not loaded

**Comment by PatrickJS** [comment]
this might be a problem with hmr where the cpu is not idle since it has an open socket for updating the client code

**Comment by Tuizi** [comment]
I put a `requestIdleCallback` in my own code, and the callback function is called as expected. But not the callback of **angular2-idle-preload**

In fact I have changed the code for:
```javascript
    if (win.requestIdleCallback) {
        console.debug(':|');
        return function (fn) {
            console.debug(':)');
            return win.requestIdleCallback(function () {
                console.debug("idle callback");
                fn();
            });
        };
    }
```

And the output is only `:|`.
It looks like the returned function is never called, I expected to see also `:)`

**Comment by PatrickJS** [comment]
@Tuizi are you using version 1.0.4?

**Comment by Tuizi** [comment]
Yes it is working 👍
