### ISSUE TITLE
Not compatible with Angular Universal

### ISSUE THREAD

**Issue by Tuizi** [AngularClass/angular2-idle-preload#5]
I try to make it work with Angular Universal. The main problem is in node: `window is not defined`

I have added:

```javascript
var mockWindow = {
    setTimeout: function(fn, time) { return gobal.setTimeout(fn, time); }
}

function _requestIdle(zone) {
    var win = typeof window === 'undefined' ? mockWindow : window;
    if (win.requestIdleCallback) {
        return function (fn) { return win.requestIdleCallback(fn); };
    }
    return function (fn) { return zone.runOutsideAngular(function () { return win.setTimeout(fn, 10); }); };
}
```

But then I get the error:

```bash
EXCEPTION: Response with status: 200 Ok for URL: null

/Users/fabienrogeret/Projects/Impressview/web/node_modules/zone.js/dist/zone-node.js:158
                        throw error;
                        ^
Response with status: 200 Ok for URL: null
```

Any idea?

**Comment by Tuizi** [comment]
In fact the error with zone-node.js is related to my project not with Angular2-idle-preload.
So the fix I did make Angular2-idle-preload works with Angular-Universal, I will do a PullRequest for it.

**Comment by PatrickJS** [comment]
you wouldn't include this is in ServerAppModule

**Comment by PatrickJS** [comment]
I added window checking if you're in nodejs or web worker
https://github.com/gdi2290/angular-idle-preload/commit/3089448de9d3ab0a7273769ddf75f20b0f345d71

**Comment by PatrickJS** [comment]
please install via `angular-idle-preload@2.0.3`
