### ISSUE TITLE
Update for angular 5

### ISSUE THREAD

**Issue by Ks89** [AngularClass/angular2-idle-preload#6]
ERROR in [at-loader] ./node_modules/@angularclass/idle-preload/dist/index.d.ts:1:39
    TS2305: Module '"MYPATH/node_modules/@angular/core/index"' has no exported member 'OpaqueToken'.
webpack: Failed to compile.

**Comment by kadosh1000** [comment]
Currently the only dependency preventing me from moving to anglar 5 :(

**Comment by ValentinFunk** [comment]
See #7, if you want to use it now:

package.json
```json
"dependencies": {
  "@angularclass/idle-preload": "https://cdn.rawgit.com/Kamshak/packages/b561a6bd/angularclass-idle-preload-v2.0.1.tgz"
}
```

**Comment by PatrickJS** [comment]
install the update via angular-idle-preload@2.0.3
