### ISSUE TITLE
Cannot find module 'rxjs/observable' error

### ISSUE THREAD

**Issue by teeSee** [AngularClass/angular2-idle-preload#8]
I got this when using angular-idle-preload@2.0.3 with rxjs@5.5.2

ERROR in node_modules/angular-idle-preload/dist/index.d.ts(2,28): error TS2307: Cannot find module 'rxjs/observable'.

Please advise. What should I do?

**Comment by PatrickJS** [comment]
@teeSee can you try angular-idle-preload@2.0.4

**Comment by teeSee** [comment]
Very Cool. It works. Thanks.

**Comment by PatrickJS** [comment]
kool, thanks for creating the issue
