### ISSUE TITLE
Angular 6 / rxjs 6 compatability

### ISSUE THREAD

**Issue by marklagendijk** [AngularClass/angular2-idle-preload#9]
Currenlty this library is not compatible with rxjs 6. Since Angular 6 requires rxjs 6 it is also not compatible with Angular 6.

```
ERROR in ./node_modules/angular-idle-preload/dist/index.js
Module not found: Error: Can't resolve 'rxjs/observable/of' in '/my-project//node_modules/angular-idle-preload/dist'
 @ ./node_modules/angular-idle-preload/dist/index.js 9:11-40
 @ ./src/environments/environment.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.routes.spec.ts
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
``` 

Until this is fixed we can use `rxjs-compat` as a workaround.

**Comment by junibrosas** [comment]
I have a problem with cannot fine module 'rxjs/observable'.

**Comment by yildiraymeric** [comment]
Hi,

I've just sent a PR for this issue, please check; https://github.com/gdi2290/angular-idle-preload/pull/11

**Comment by PatrickJS** [comment]
3.0.0 published
